name: Run tests uwu

on:
  push:
    branches: [ "main" ]
    paths:
      - src/**
      - tests/**
      - Cargo.toml
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**
      - tests/**
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo build
        run: cargo build --verbose

      - name: Run cargo test
        run: cargo test
